spring:
  application:
    name: consumer-one
server:
  port: 8080
dubbo:
  protocol:
#    serialization: java
  registry:
    address: zookeeper://47.105.97.246:2181
    id: my-registry
    register: false
#    check: false
  application:
    name: consumer-one
#  consumer:
#    check: false